### PR TITLE
Use wtype for typing under Wayland

### PR DESCRIPTION
**Pull request by markstos**
Here's a PR to fix typing under Wayland to address #12.

I produced this quickly before dinner and it still needs some real-world testing.

### CODE REVIEW

**Comment by emlun** [comment]
Great idea! `xdotool` has actually worked fine for me in Wayland, though, so I've updated it to check for presence of either binary (preferring `wtype` if available) instead of relying on the environment variable. Thanks for the contribution!

**Comment by markstos** [comment]
Thanks for the fast response and fix.

This issue in the `xdotool` tracker seems to re-affirm that `xdotool` doesn't work under Wayland, yet another commenter there also says it "works for them". 

https://github.com/jordansissel/xdotool/issues/282

As I commented there, maybe it works when `XWayland` is running under Wayland?

If that's the case, I know some people are trying to run "Wayland-only" environments without XWayland.

**Comment by emlun** [comment]
Ah, yeah, it could have to do with some kind of compatibility adapter. I noticed it did not work while I had Alacritty focused, but did work with Firefox. Either way, preferring `wtype` over `xdotool` when possible should support both use cases. :slightly_smiling_face:

**Comment by markstos** [comment]
Alacritty is nice! I've been testing the new Vi selection mode in the 0.5.0 release candidate. It's not particularly documented, but I was able to figure out enough from the shipped alacritty.yml file.

**Pull request merged**
