### PR TITLE
#19 Compatibility with yubikey-manager v4

### LINKED ISSUE #19: No module named 'ykman.driver_ccid' with yubikey-manager version > 4.x
Hi,
looks like the `driver_ccid` is gone with the latest `ykman` module from the yubikey-manager.

```
❯ /usr/bin/yubikey-oath-dmenu
Traceback (most recent call last):
  File "/usr/bin/yubikey-oath-dmenu", line 25, in <module>
    import ykman.driver_ccid
ModuleNotFoundError: No module named 'ykman.driver_ccid'
```

Working on the fix right now.

### PR DESCRIPTION
**Pull request by stibi**
Fixes #19

Compatibility with yubikey-manager v4.

### CODE REVIEW

**Comment by markstos** [comment]
I've tested that both these work:

```
./yubikey-oath-dmenu.py --menu-cmd 'rofi -dmenu -p "Credentials" -i' --clipboard --clipboard-cmd wl-copy
./yubikey-oath-dmenu.py --stdout
```

What's needed turn this WIP/Draft PR into a released PR?

**Comment by stibi** [comment]
@markstos thanks for the bump.

@emlun what do you think? Anything to add / change?

**Comment by emlun** [comment]
Thanks! I'll have a look later today or by the end of the week at worst.

**Comment by markstos** [comment]
I think there's a problem that I didn't notice at first. In the list shown in dmenu, I think only the "usernames" are shown. I have many OTPs and several have similar user names. I believe before the service name should also show in the list.  Ideally, both are included because sometimes I have multiple logins with the same service, each with unique OTPs.

**Comment by emlun** [comment]
Sorry for being a bit slow. I found and fixed a couple more things, but all in all this seems to be working great! Thanks to both of you!

**Pull request merged**
